services:
  db:
    container_name: db
    image: postgres
    volumes:
      - storage_db:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase

  api:
    container_name: api
    build: .
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:root@db:5432/mydatabase"

volumes:
  storage_db:
